[deps]
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
julia = "1.6"
Gen = "0.4, 0.5"
Distributions = "0.25"
Combinatorics = "1.0"